### ISSUE TITLE
Suggestions for Environment setup document

### ISSUE THREAD

**Issue by dmopalmer** [krtkl/snickerdoodle-manual#1]
I followed along with the Snickerdoodle Development Environment Setup (Ubuntu) document on a fresh virtual machine.  (Hosted on OS X, which probably doesn't matter.)

Two things:
1) After you install the Xilinx tools with 
`sudo ./Xilinx_Vivado_SDK_2015.4_1118_2_Lin64.bin` you are left with a directory owned by root in your home directory.  You then must use
`sudo chown -R <username> ~/.Xilinx`
so that the program will be runnable by the user without sudo.

2) Rather than manually add to the path, Xilinx offers a source script to set up the environment.  
`source /opt/Xilinx/Vivado/2015.4/settings64.sh`

**Comment by russbush** [comment]
Good catch with the ownership permissions.

The problem with sourcing the setup scripts is that this method requires the scripts to be sourced with every new terminal session. The settingsXX.sh scripts actually source a series of other scripts that are responsible for setting up the environment with a $PATH that points to directories containing the SDK and DocNav binaries. This $PATH will not persist beyond the current terminal session. Fortunately, there are a couple options:
1. Source the script from within the user’s .bashrc or .profile file which will remove the manual step of sourcing the settingsXX.sh 
2. Include the directories within the /etc/environment specification of $PATH
   > This method will make the $PATH persistent for ALL users (which may or may not be what you want).

There are also some library sourcing parts of the script that set $LD_LIBRARY_PATH which should be done from within /etc/ld.so.conf.d/*.conf files rather than setting the variable directly. 

I’ll be updating the installation guides to include these steps/suggestions. Thanks for the feedback.
