### ISSUE TITLE
404 on boardfile link in hardware config manual

### ISSUE THREAD

**Issue by rbarris** [krtkl/snickerdoodle-manual#2]
This link to the Vivado board files for Snickerdoodle is not correct or not yet available:

 https://github.com/krtkl/snickerdoodle-board-files/archive/master.zip

**Comment by russbush** [comment]
Hi Rob,

The board files that were previously posted to that repo were not up to date and were causing issues for people that were starting new projects. The current approach for new projects is to use the example projects as a starting point until new board files are generated. Because none of he FPGA I/O have been pre-allocated for things like LEDs (as you see with other Zynq boards) the only thing you need to start a project is the processing subsystem IP configuration from the example projects. I am working on getting correct board files and re-uploadng to the repo you referenced but in the interim the examples will give you something to work with. Thanks and please don't hesitate to let me know if you need anything else or have any other questions. 

Russell Bush

**Comment by rbarris** [comment]
Yup no prob

Are the schematics on github in sync?

**Comment by Weatherbee** [comment]
Hi Rob, snickerdoodle is on rev 2.  As we just received the rev 3. boards I will post an update to bring it up to sync.

-Jamil
